src/Front/ConfigBundle/Entity/Media.php
<?php

namespace Front\ConfigBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\validator\Constraints as Assert;

/**
 * Media
 *
 * @ORM\Table("ost_front_vo")
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */
class Media
{

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     * 
     * @ORM\COlumn(name="updated_at",type="datetime", nullable=true) 
     */
    private $updateAt;

    /**
     * @ORM\PostLoad()
     */
    public function postLoad()
    {
	$this->updateAt = new \DateTime();
    }

    /**
     * @ORM\Column(type="string",length=255, nullable=true) 
     */
    public $path;
    public $file;

    public function getUploadRootDir()
    {
	return __dir__ . '/../../../../web/' . $this->getDirectory();
    }

    public function getDirectory()
    {
	    return 'uploads/VoyageOrganise/BlocMetro';
    }

    public function getAssetPath()
    {
	return $this->getDirectory() . '/' . $this->path;
    }

    public function getAbsolutePath()
    {
	return null === $this->path ? null : $this->getUploadRootDir() . '/' . $this->path;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate() 
     */
    public function preUpload()
    {
	$this->tempFile = $this->getAbsolutePath();
	$this->oldFile = $this->getPath();
	$this->updateAt = new \DateTime();

	if (null !== $this->file)
	    $this->path = sha1(uniqid(mt_rand(), true)) . '.' . $this->file->guessExtension();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate() 
     */
    public function upload()
    {
	if (null !== $this->file)
	{
	    $this->file->move($this->getUploadRootDir(), $this->path);
	    unset($this->file);
	    if ($this->oldFile != null && file_exists($this->tempFile))
		unlink($this->tempFile);
	}
    }

    /**
     * @ORM\PreRemove() 
     */
    public function preRemoveUpload()
    {
	$this->tempFile = $this->getAbsolutePath();
    }

    /**
     * @ORM\PostRemove() 
     */
    public function removeUpload()
    {
	if (file_exists($this->tempFile))
	    unlink($this->tempFile);
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
	return $this->id;
    }

    public function getPath()
    {
	return $this->path;
    }

    /**
     * Set updateAt
     *
     * @param \DateTime $updateAt
     * @return Media
     */
    public function setUpdateAt($updateAt)
    {
	$this->updateAt = $updateAt;

	return $this;
    }

    /**
     * Get updateAt
     *
     * @return \DateTime 
     */
    public function getUpdateAt()
    {
	return $this->updateAt;
    }

    /**
     * Set path
     *
     * @param string $path
     * @return Media
     */
    public function setPath($path)
    {
	$this->path = $path;

	return $this;
    }

    public function __toString()
    {
	return $this->getAssetPath();
    }
}

src/Front/ConfigBundle/Controller/VoyageOrganiseController.php
<?php
    namespace Front\ConfigBundle\Controller;

    use Symfony\Bundle\FrameworkBundle\Controller\Controller;
    use Symfony\Component\HttpFoundation\Session\Session;
    use Front\ConfigBundle\Entity\TopDestination;
    use Front\ConfigBundle\Form\TopDestinationType;
    use Front\ConfigBundle\Entity\SliderVO;
    use Front\ConfigBundle\Form\SliderVOType;
    use Front\ConfigBundle\Entity\BlockMetro;
    use Front\ConfigBundle\Form\BlockMetroType;

    class VoyageOrganiseController extends Controller
    {
        public function topDestinationAction($id)
        {
            $em = $this->getDoctrine()->getManager();
            $session = $this->getRequest()->getSession();
            $request = $this->getRequest();
            if(is_null($id))
                $topDestnation = new TopDestination();
            else
                $topDestnation = $em->getRepository('FrontConfigBundle:TopDestination')->find($id);
            $topDestnations = $em->getRepository('FrontConfigBundle:TopDestination')->findBy(array(),array('ordre' => 'asc'));
            $form = $this->createForm(new TopDestinationType(),$topDestnation);
            if($request->isMethod('POST')){
                $form->submit($request);
                if($form->isValid()){
                    $topDestnation = $form->getData();
                    $em->persist($topDestnation);
                    $em->flush();
                    $session->getFlashBag()->add('success',"Votre top destination a été mise a jour avec succès ");
                    return $this->redirect($this->generateUrl("front_config_voyageorganise_topdestination"));
                }
            }
            return $this->render('FrontConfigBundle:VoyageOrganise:topDestination.html.twig',array(
                'topDestinations' => $topDestnations,
                'form'            => $form->createView(),
            ));
        }

        public function deleteTopDestinationAction(TopDestination $topDestination)
        {
            $em = $this->getDoctrine()->getManager();
            $session = $this->getRequest()->getSession();
            $em->remove($topDestination);
            $em->flush();
            $session->getFlashBag()->add('success'," Votre top destination a été supprimé avec succées ");
            return $this->redirect($this->generateUrl('front_config_voyageorganise_topdestination'));
        }

        public function showTopDestinationAction()
        {
            $em = $this->getDoctrine()->getManager();
            $topDestinations = $em->getRepository('FrontConfigBundle:TopDestination')->findBy(array(),array('ordre' => 'asc'));
            return $this->render('FrontConfigBundle:VoyageOrganise:showTopDestination.html.twig',array(
                'topDestinations' => $topDestinations,
            ));
        }

        public function sliderAction($id)
        {
            $em = $this->getDoctrine()->getManager();
            $session = $this->getRequest()->getSession();
            $request = $this->getRequest();
            if(is_null($id))
                $slider = new SliderVO();
            else
                $slider = $em->getRepository('FrontConfigBundle:SliderVO')->find($id);
            $sliders = $em->getRepository('FrontConfigBundle:SliderVO')->findBy(array(),array('ordre' => 'asc'));
            $form = $this->createForm(new SliderVOType(),$slider);
            if($request->isMethod('POST')){
                $form->submit($request);
                if($form->isValid()){
                    $slider = $form->getData();
                    $em->persist($slider);
                    $em->flush();
                    $session->getFlashBag()->add('success',"Votre slider a été mise a jour avec succès ");
                    return $this->redirect($this->generateUrl("front_config_voyageorganise_slider"));
                }
            }
            return $this->render('FrontConfigBundle:VoyageOrganise:slider.html.twig',array(
                'sliders' => $sliders,
                'form'    => $form->createView(),
            ));
        }

        public function deleteSliderAction(SliderVO $slider)
        {
            $em = $this->getDoctrine()->getManager();
            $session = $this->getRequest()->getSession();
            $em->remove($slider);
            $em->flush();
            $session->getFlashBag()->add('success'," Votre slider a été supprimé avec succées ");
            return $this->redirect($this->generateUrl('front_config_voyageorganise_slider'));
        }

        public function blockMetroAction()
        {
            $em = $this->getDoctrine()->getManager();
            $session = $this->getRequest()->getSession();
            $blockMetro = $em->getRepository('FrontConfigBundle:BlockMetro')->find(1);
            if(!$blockMetro)
                $blockMetro = new BlockMetro();
            $form = $this->createForm(new BlockMetroType(),$blockMetro);
            $request = $this->getRequest();
            if($request->isMethod('POST')){
                $form->submit($request);
                if($form->isValid()){
                    $blockMetro = $form->getData();
                    $em->persist($blockMetro);
                    $em->flush();
                    $session->getFlashBag()->add('success',"Votre Block metro a été mise a jour avec succès ");
                    return $this->redirect($this->generateUrl("front_config_voyageorganise_blockmetro"));
                }
            }
            return $this->render('FrontConfigBundle:VoyageOrganise:blockMetro.html.twig',array(
                'form'       => $form->createView(),
                'blockMetro' => $blockMetro,
            ));
        }

        public function showBlockMetroAction()
        {
            $em = $this->getDoctrine()->getManager();
            $blockMetro = $em->getRepository('FrontConfigBundle:BlockMetro')->find(1);
            return $this->render('FrontConfigBundle:VoyageOrganise:showBlockMetro.html.twig',array(
                'blockMetro' => $blockMetro,
            ));
        }
    }

src/Front/ConfigBundle/Resources/views/VoyageOrganise/blockMetro.html.twig
{% extends ":Back:base.html.twig" %}
{% block title %}Idées Voyages{% endblock %}
{% block topbody %}   
    {{ parent() }}
    <li>
        <a href="javascript:void(0)" >{{ block('title') }}</a>
    </li>
{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    {{ form_start(form) }}
                    <div class="row">
                        {{ formulaire.input("col-md-3","Libelle",form.libelle,true) }}
		    </div>
		    <div class="row">
			{{ formulaire.input("col-md-3","Theme 1",form.theme1,true) }}
			{{ formulaire.input("col-md-4","Photo 1 (290 x 209)",form.photo1.file,true) }}
			<div class="col-md-4">
			    <img src="{{ asset(blockMetro.photo1.assetPath) }}" style="width: 50px;height: 50px">
			</div>
		    </div>
		    <div class="row">
			{{ formulaire.input("col-md-3","Theme 2",form.theme2,true) }}
			{{ formulaire.input("col-md-4","Photo 2 (290 x 209)",form.photo2.file,true) }}
			<div class="col-md-4">
			    <img src="{{ asset(blockMetro.photo2.assetPath) }}" style="width: 50px;height: 50px">
			</div>
		    </div>
		    <div class="row">
			{{ formulaire.input("col-md-3","Theme 3",form.theme3,true) }}
			{{ formulaire.input("col-md-4","Photo 3 (590 x 209)",form.photo3.file,true) }}
			<div class="col-md-4">
			    <img src="{{ asset(blockMetro.photo3.assetPath) }}" style="width: 50px;height: 50px">
			</div>
		    </div>
		    <div class="row">
			{{ formulaire.input("col-md-3","Theme 4",form.theme4,true) }}
			{{ formulaire.input("col-md-4","Photo 4 (290 x 209)",form.photo4.file,true) }}
			<div class="col-md-4">
			    <img src="{{ asset(blockMetro.photo4.assetPath) }}" style="width: 50px;height: 50px">
			</div>
		    </div>
		    <div class="row">
			{{ formulaire.input("col-md-3","Theme 5",form.theme5,true) }}
			{{ formulaire.input("col-md-4","Photo 5 (290 x 209)",form.photo5.file,true) }}
			<div class="col-md-4">
			    <img src="{{ asset(blockMetro.photo5.assetPath) }}" style="width: 50px;height: 50px">
			</div>
		    </div>
		    <div class="row">
			{{ formulaire.input("col-md-3","Theme 6",form.theme6,true) }}
			{{ formulaire.input("col-md-4","Photo 6 (590 x 209)",form.photo6.file,true) }}
			<div class="col-md-4">
			    <img src="{{ asset(blockMetro.photo6.assetPath) }}" style="width: 50px;height: 50px">
			</div>
		    </div>
		    <div class="row">
			{{ formulaire.input("col-md-3","Theme 7",form.theme7,true) }}
			{{ formulaire.input("col-md-4","Photo 7 (290 x 209)",form.photo7.file,true) }}
			<div class="col-md-4">
			    <img src="{{ asset(blockMetro.photo7.assetPath) }}" style="width: 50px;height: 50px">
			</div>
		    </div>
		    <div class="row">
			{{ formulaire.input("col-md-3","Theme 8",form.theme8,true) }}
			{{ formulaire.input("col-md-4","Photo 8 (290 x 209)",form.photo8.file,true) }}
			<div class="col-md-4">
			    <img src="{{ asset(blockMetro.photo8.assetPath) }}" style="width: 50px;height: 50px">
			</div>
		    </div>
		    <div class="no-display">
			{% for i in 1..8 %}
			{{ formulaire.input("col-md-3","Theme 8",form['photo'~i].updateAt,true) }}
			{% endfor %}
		    </div>
                    {{ formulaire.submit("Enregistrer") }}
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/Front/ConfigBundle/Resources/views/VoyageOrganise/showBlockMetro.html.twig
{% if blockMetro %}
    <div class="row pt-50 pb-30">
	<div class="col-xs-12 col-sm-3 col-md-3 rs-mb" style="padding: 0px 5px 5px 5px;">
	    <div class="list-item-image">
		<div class="image-inner">
		    <a class="" href="{{ path('front_voyageorganise_liste',{'themes':blockMetro.theme1.id}) }}">
			<img src="{{ asset(blockMetro.photo1) }}" alt="Image" style="width: 290px;height: 209px">
			<div class="image-overlay">
			    <div class="overlay-content">
				<div class="overlay-icon" style="border: none;"><i>{{ blockMetro.theme1 }}</i></div>
			    </div>	
			</div>
		    </a>	
		</div>
	    </div>
	</div>
	<div class="col-xs-12 col-sm-3 col-md-3 xs-mb" style="padding: 0px 5px 5px 5px;">
	    <div class="list-item-image">
		<div class="image-inner">
		    <a class="" href="{{ path('front_voyageorganise_liste',{'themes':blockMetro.theme2.id}) }}">
			<img src="{{ asset(blockMetro.photo2) }}" alt="Image" style="width: 290px;height: 209px">
			<div class="image-overlay">
			    <div class="overlay-content">
				<div class="overlay-icon" style="border: none;"><i>{{ blockMetro.theme2 }}</i></div>
			    </div>	
			</div>
		    </a>	
		</div>
	    </div>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-6 xs-mb" style="padding: 0px 5px 5px 5px;">
	    <div class="list-item-image">
		<div class="image-inner">
		    <a class="" href="{{ path('front_voyageorganise_liste',{'themes':blockMetro.theme3.id}) }}">
			<img src="{{ asset(blockMetro.photo3) }}" alt="Image" style="width: 590px;height: 209px">
			<div class="image-overlay">
			    <div class="overlay-content">
				<div class="overlay-icon" style="border: none;"><i>{{ blockMetro.theme3 }}</i></div>
			    </div>	
			</div>
		    </a>	
		</div>
	    </div>
	</div>
	<div class="col-xs-12 col-sm-3 col-md-3 rs-mb" style="padding: 5px 5px 5px 5px;">
	    <div class="list-item-image">
		<div class="image-inner">
		    <a class="" href="{{ path('front_voyageorganise_liste',{'themes':blockMetro.theme4.id}) }}">
			<img src="{{ asset(blockMetro.photo4) }}" alt="Image" style="width: 290px;height: 209px">
			<div class="image-overlay">
			    <div class="overlay-content">
				<div class="overlay-icon" style="border: none;"><i>{{ blockMetro.theme4 }}</i></div>
			    </div>	
			</div>
		    </a>	
		</div>
	    </div>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-6 xs-mb" style="padding: 5px 5px 5px 5px;">
	    <div style="width: 590px;height: 209px;background-color: #3C454E;    padding: 70px;">
		<h1 style="color: white;font-size: 60px;text-align: center;">{{ blockMetro.libelle }}</h1>
	    </div>
	</div>
	<div class="col-xs-12 col-sm-3 col-md-3 xs-mb" style="padding: 5px 5px 5px 5px;">
	    <div class="list-item-image">
		<div class="image-inner">
		    <a class="" href="{{ path('front_voyageorganise_liste',{'themes':blockMetro.theme5.id}) }}">
			<img src="{{ asset(blockMetro.photo5) }}" alt="Image" style="width: 290px;height: 209px">
			<div class="image-overlay">
			    <div class="overlay-content">
				<div class="overlay-icon" style="border: none;"><i>{{ blockMetro.theme5 }}</i></div>
			    </div>	
			</div>
		    </a>
		</div>
	    </div>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-6 xs-mb" style="padding: 5px 5px 5px 5px;">
	    <div class="list-item-image">
		<div class="image-inner">
		    <a class="" href="{{ path('front_voyageorganise_liste',{'themes':blockMetro.theme6.id}) }}">
			<img src="{{ asset(blockMetro.photo6) }}" alt="Image" style="width: 590px;height: 209px">
			<div class="image-overlay">
			    <div class="overlay-content">
				<div class="overlay-icon" style="border: none;"><i>{{ blockMetro.theme6 }}</i></div>
			    </div>	
			</div>
		    </a>	
		</div>
	    </div>
	</div>
	<div class="col-xs-12 col-sm-3 col-md-3 rs-mb" style="padding: 5px 5px 5px 5px;">
	    <div class="list-item-image">
		<div class="image-inner">
		    <a class="" href="{{ path('front_voyageorganise_liste',{'themes':blockMetro.theme7.id}) }}">
			<img src="{{ asset(blockMetro.photo7) }}" alt="Image" style="width: 290px;height: 209px">
			<div class="image-overlay">
			    <div class="overlay-content">
				<div class="overlay-icon" style="border: none;"><i>{{ blockMetro.theme7 }}</i></div>
			    </div>	
			</div>
		    </a>	
		</div>
	    </div>
	</div>
	<div class="col-xs-12 col-sm-3 col-md-3 xs-mb" style="padding: 5px 5px 5px 5px;">
	    <div class="list-item-image">
		<div class="image-inner">
		    <a class="" href="{{ path('front_voyageorganise_liste',{'themes':blockMetro.theme8.id}) }}">
			<img src="{{ asset(blockMetro.photo8) }}" alt="Image" style="width: 290px;height: 209px">
			<div class="image-overlay">
			    <div class="overlay-content">
				<div class="overlay-icon" style="border: none;"><i>{{ blockMetro.theme8 }}</i></div>
			    </div>	
			</div>
		    </a>	
		</div>
	    </div>
	</div>
    </div>
{% endif %}

src/Front/ConfigBundle/Resources/views/VoyageOrganise/showTopDestination.html.twig
{% if topDestinations|length >0 %}
    <div class="row clearfix pv-30 mt-20">
	<div class="col-xs-12 col-sm-12 col-md-12 mt-30">
	    <h3 class="section-title mv-30">Top destinations voyages organisés</h3>
	</div>
	<div class="produc-item">
	    {% for topDestination in topDestinations %}
		<div class="col-xs-12 col-sm-6 col-md-3">
		    <div class="list-item">
			<div class="list-item-image">
			    <div class="image-inner">
				<a class="link-image" href="{{ path('front_voyageorganise_liste',{'destinations':topDestination.destination.id}) }}">
				    <img src="{{ asset(topDestination.assetPath) }}" alt="Image" style="width: 270px;height: 195px" />
				</a>	
			    </div>
			</div><!-- end list-item -->
			<div class="list-item-label">
			    <h4 class="list-item-title"><a href="{{ path('front_voyageorganise_liste',{'destinations':topDestination.destination.id}) }}">{{ topDestination.destination }}</a></h4>
			    <div class="list-item-price">
				<a href="{{ path('front_voyageorganise_liste',{'destinations':topDestination.destination.id}) }}"><i class="fa-arrow-right"></i></a>
			    </div>
			</div>
		    </div>
		</div>
	    {% endfor %}
	</div>
    </div>
{% endif %}

src/Front/ConfigBundle/Resources/views/VoyageOrganise/slider.html.twig
{% extends ":Back:base.html.twig" %}
{% block title %}Slider{% endblock %}
{% block topbody %}   
    {{ parent() }}
    <li>
        <a href="javascript:void(0)" >{{ block('title') }}</a>
    </li>
{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    {{ form_start(form) }}
                    <div class="row">
                        {{ formulaire.input("col-md-3","Titre1",form.titre1,true) }}
                        {{ formulaire.input("col-md-3","Titre2",form.titre2,true) }}
                        {{ formulaire.input("col-md-3","Titre3",form.titre3,true) }}
                        {{ formulaire.input("col-md-3","Url",form.url,true) }}
		    </div>
		    <div class="row">
                        {{ formulaire.input("col-md-2","Ordre",form.ordre,true) }}
                        {{ formulaire.input("col-md-4","Photo (1350 x 560)",form.file,true) }}
                    </div>
                    {{ formulaire.submit("Enregistrer") }}
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover table-full-width table-condensed table-hover"  id="sample_1">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Titre 1</th>
                                <th>Titre 2</th>
                                <th>Titre 3</th>
                                <th>Url</th>
                                <th>Ordre</th>
                                <th class="center" >Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for slider in sliders %}
                                <tr>
                                    <td class="center"><img src="{{ asset(slider.assetPath) }}" style="width: 50px;height: 50px"></td>
                                    <td>{{ slider.titre1 }}</td>
                                    <td>{{ slider.titre2 }}</td>
                                    <td>{{ slider.titre3 }}</td>
                                    <td>{{ slider.url }}</td>
                                    <td>{{ slider.ordre }}</td>
                                    <td class="TableAction">
                                        <div class="visible-md visible-lg hidden-sm hidden-xs">
                                            {{ macros.tableEdit(path('front_config_voyageorganise_slider',{'id':slider.id})) }}
                                            {{ macros.tableDelete(path('front_config_voyageorganise_slider_delete',{'id':slider.id})) }}
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/Front/ConfigBundle/Resources/views/VoyageOrganise/topDestination.html.twig
{% extends ":Back:base.html.twig" %}
{% block title %}Top Destination{% endblock %}
{% block topbody %}   
    {{ parent() }}
    <li>
        <a href="javascript:void(0)" >{{ block('title') }}</a>
    </li>
{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    {{ form_start(form) }}
                    <div class="row">
                        {{ formulaire.input("col-md-3","Destination",form.destination,true) }}
                        {{ formulaire.input("col-md-2","Ordre",form.ordre,true) }}
                        {{ formulaire.input("col-md-4","Photo (270 x 195)",form.file,true) }}
                    </div>
                    {{ formulaire.submit("Enregistrer") }}
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover table-full-width table-condensed table-hover"  id="sample_1">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Destination</th>
                                <th>Ordre</th>
                                <th class="center" >Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for topDestination in topDestinations %}
                                <tr>
                                    <td class="center"><img src="{{ asset(topDestination.assetPath) }}" style="width: 50px;height: 50px"></td>
                                    <td>{{ topDestination.destination }}</td>
                                    <td>{{ topDestination.ordre }}</td>
                                    <td class="TableAction">
                                        <div class="visible-md visible-lg hidden-sm hidden-xs">
                                            {{ macros.tableEdit(path('front_config_voyageorganise_topdestination',{'id':topDestination.id})) }}
                                            {{ macros.tableDelete(path('front_config_voyageorganise_topdestination_delete',{'id':topDestination.id})) }}
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}